#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'imgui'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
        '../thirdparty/imgui/imgui.cpp',
        '../thirdparty/imgui/imgui_draw.cpp',
        '../thirdparty/imgui/imgui_tables.cpp',
        '../thirdparty/imgui/imgui_widgets.cpp',
        '../thirdparty/imgui/imgui_demo.cpp',
        'imgui_impl_source.cpp',
        'imgui_system.cpp'
    ]
	
	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
	    '../public/tier3',
		'../common',
		'../thirdparty/imgui',
	]		
	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'	

	defines = []	
	libs = [
		'tier0',
		'particles',
		'dmxloader',
		'vgui_controls',
		'matsys_controls',
		'tier1',
		'tier2',
		'tier3',
		'mathlib',
		'vstdlib',
		'choreoobjects',
		'steam_api',
		'bitmap',
		'vtf',
		'RT',
		'ZLIB',
		'SDL2',
		'filesystem',
		'materialsystem',
	]
	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']
	
	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

