#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'good'

def configure(conf):
	pass

def build(bld):
	source = [
		'src/thread.cpp',
		'src/process.cpp',
		'src/mutex.cpp',
		'src/log.cpp',
		'src/ini_file.cpp',
		'src/file.cpp',
	]

	includes = [
		'include',
	]

	defines = [
		'GOOD_INI_ONE_KV_SEPARATOR',
		'GOOD_INI_ONE_COMMENT_CHAR',
		'GOOD_LOG_FLUSH',
		'GOOD_LOG_USE_ENDL',
	]

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		idx      = bld.get_taskgen_count()
	)
